server:
  port: 8091

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:

      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
analyzer:
  api:
    prefix: /api/v1