server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mg_test
    username: quadalus
    password: pollka78
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

analyzer:
  api:
    prefix: /api/v1