CREATE TABLE IF NOT EXISTS market_spread
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pair VARCHAR NOT NULL,
    market_base_name VARCHAR(50) NOT NULL,
    market_base_price NUMERIC NOT NULL,
    market_base_volume NUMERIC NOT NULL,
    market_quote_name VARCHAR(50) NOT NULL,
    market_quote_price  NUMERIC NOT NULL,
    market_quote_volume NUMERIC NOT NULL,
    spread NUMERIC NOT NULL,
    time  TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS market_coin_info
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coin_name VARCHAR NOT NULL,
    market_name VARCHAR(50) NOT NULL,
    market_deposit_network_name VARCHAR NOT NULL,
    market_network_is_deposit BOOLEAN NOT NULL,
    market_withdraw_network_name VARCHAR NOT NULL,
    market_network_is_withdraw BOOLEAN NOT NULL
);
