server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

parser:
  api:
    base:
      coin_uri: /parser/coin/info
      prefix: /api/v1
      kline_uri: /parser/klines
      order_book_uri: /parser/depth
      analyzer_url: ${ANALYZER_SERVER_URL}
      analyzer_port: 8091
      analyzer_kline_uri: /analyzer/klines
      analyzer_order_book_uri: /analyzer/depth
      binance_url: ${BINANCE_SERVER_URL}
      bybit_url: ${BYBIT_SERVER_URL}
      okx_url: ${OKX_SERVER_URL}
      mexc_url: ${MEXC_SERVER_URL}
      huobi_url: ${HUOBI_SERVER_URL}