server:
  port: 8080

spring:
  datasource:
    host: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

parser:
  api:
    base:
      coin_uri: /parser/coin/info
      prefix: /api/v1
      kline_uri: /parser/klines
      order_book_uri: /parser/depth
      analyzer_host: ${ANALYZER_SERVER_HOST}
      analyzer_port: 8091
      analyzer_kline_uri: /analyzer/klines
      analyzer_order_book_uri: /analyzer/depth
      binance_host: ${BINANCE_SERVER_HOST}
      bybit_host: ${BYBIT_SERVER_HOST}
      okx_host: ${OKX_SERVER_HOST}
      mexc_host: ${MEXC_SERVER_HOST}
      huobi_host: ${HUOBI_SERVER_HOST}