server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/binanceTest
    username: quadalus
    password: pollka78
    driver-class-name: org.postgresql.Driver

binance:
  api:
    key: wvErOOsXHh3W3MXH9fDpVmHf0oxxKw2OqCUKENxU7InUXlMjbCQre5r8Kbh4EvJJ
    secret: ZupmdECgPFktUEvwgvJ18qu84paxJhHubpAw2LsSEV8CuL5KNc99U13GEEK6bbyt