server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

binance:
  api:
    key:
    secret: